# Generated by Django 2.2.7 on 2019-11-19 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleText', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Services', 'Services'), ('Miscellaneous', 'Miscellaneous'), ('Housing', 'Housing'), ('Food', 'Food'), ('Community', 'Community'), ('Textbooks', 'Textbooks'), ('Tutoring', 'Tutoring'), ('Clothes', 'Clothes')], default='Miscellaneous', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('file', models.ImageField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentPostID', models.IntegerField()),
                ('commentDescription', models.CharField(max_length=800)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
