# Generated by Django 2.2.5 on 2019-11-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='file'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
