# Generated by Django 2.2.5 on 2019-11-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Services', 'Services'), ('Misc', 'Miscellaneous'), ('Housing', 'Housing'), ('Food', 'Food'), ('Community', 'Community'), ('Textbooks', 'Textbooks'), ('Tutoring', 'Tutoring'), ('Clothes', 'Clothes')], default='Misc', max_length=200),
        ),
    ]
