# Generated by Django 2.2.6 on 2019-10-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='category0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
