# Generated by Django 2.2.5 on 2019-11-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Services', 'Services'), ('Misc', 'Miscellaneous')], default='Misc', max_length=200),
        ),
    ]
