# Generated by Django 2.2.5 on 2019-11-06 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191106_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Services', 'Services'), ('Misc', 'Miscellaneous'), ('Housing', 'Housing'), ('Food', 'Food'), ('Community', 'Community'), ('Textbooks', 'Textbooks'), ('Tutoring', 'Tutoring'), ('Clothes', 'Clothes')], default='Misc', max_length=200),
        ),
    ]
