# Generated by Django 2.2.6 on 2019-11-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191101_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Services', 'Services'), ('Misc', 'Miscellaneous')], default='Misc', max_length=200),
        ),
    ]
