# Generated by Django 2.2.5 on 2019-11-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Photo'),
        ),
    ]
