# Generated by Django 2.2.5 on 2019-10-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191021_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.CharField(max_length=200),
        ),
    ]
