# Generated by Django 2.2.7 on 2019-11-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentPostID',
            field=models.IntegerField(default=0),
        ),
    ]
