# Generated by Django 2.2.7 on 2019-11-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191117_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDescription',
            field=models.TextField(max_length=800),
        ),
    ]
