# Generated by Django 2.2.5 on 2019-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191117_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDescription',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentPostID',
            field=models.IntegerField(),
        ),
    ]
