# Generated by Django 2.2.5 on 2019-11-10 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191110_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
