# Generated by Django 2.2.5 on 2019-11-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191110_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Photo'),
            preserve_default=False,
        ),
    ]
