# Generated by Django 2.2.5 on 2019-11-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
    ]
