# Generated by Django 2.2.5 on 2019-11-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191118_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=1, max_digits=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=1, max_digits=17),
            preserve_default=False,
        ),
    ]
