language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: qOkNQUFXkDQA1rOk7+4DBRZw7vl7YcG8GMH/yEIasriJKFGQIkNW4gRXnFgOlEH/XgnwHw3gLtJzqoPouK0iNJkrVt3RZmd6zO8YEtUeZB42uIkjyU6WtFmD7PEqPG3ltLoAS2JBpDrk7vEbpYrSup1DYAxFlo53+RCmq0LyK66jiGOVfQtFPnZKf0o/kfiw1Gw4MJa5nhkaGWFghrTBMDTMd16X3IF2u24A5wag/y+ZI44KG/NkCJ54UWUDbxIjnNLDNx3NMjesYBlZOK+HDaRxvfrlcE8Bdhln7bYjiSsaxnkIBP2kYzTT2BPTvxWLufONZbium1na9o8wwMGfsRwI9O/OPrFu8LCdbSdyLJ+nk4ZjxWahdhp0TYM6DKuLc2oc4lwhZ4IFF+2+r0oNL4CNqn/LUyyyE7nmDwSuKoh5fgfEqsgg5TxtuJdsMQpO/ElWN88N17+0vowTY7nfQj2zW05+lWrHtqb6wC0eVeUneNOvP4xr39m8qKCXNu43FZHpAdpZze2sOzm5R9F7JRq/35OcpumSVyeuXsLGfT+c0xw5oljfpUWOPC7FoKmVOr3MNR+HaN/zNb24BDZVYqsn83Eq61d/abj2P5FpJQFXATncRzB6GOfd1gBkslPsC0Pl0ewlzgQ6rfcqsqLhJEtA9o2IkKj1Z9Y1fF5+Fxw=
  app: renamelater-craigslist
  on:
    repo: uva-cs3240-f19/project-103-renamelater
