language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: HwmPhv/XmdPTvovnMOeMrFuKSIy/RrFxYP3x1tU0jkwxp65d8dnifxL54oCwZum2MRekfKOuuP54Ae0QspupzvEgu2MFCZYGHnazRCSq8OSPJenrN9Yaem5LfX4gLSdWBeGCnmRix5ftc3uPC7l7Cam0NxAXnSOS1UuHbxDju1xN0aTFO+hfRrgAl76LSNOZh5Yj8SpuYkPpvpvkKKjcGHnEpHXoSl3qIkEEesVIMJqxpD6qkviMe1E89MOfD/HqgDwk130wOyR6KRHx5tO1/W3bQY3FZfA3EeUMPuIV+DV7zv4GCBslfskjsGTq9WNilm2MiBNXbsC2ch/99m7PufRcPf7HDO0MNGsZdnHfxAsN7LZPF9AgTBT9FVaeBFpu4BhxZcmolPxmzJJtys2Xrng2VTG9ahg3jRVYcDIzhhd1N8TYIbiWitYTOKQzW8Z7h0kAHNnVk1xtPMF9K0fNN1eWlDaAtQyr5g7AUX4ggJbGF3Z9vYqQXxNUKRHYMq+gYZGt13NbOoQKRZvU/1XKfO6ag8rhAdUTHkrMWisiWTYH8SCn2z4UYV4LLU4VdVet1Lz48OuSUl5hjyurz20itSZRa75mflv1eDoAsBN+kZhIgxzVrvPi54rhT/vgfZBjPlaAfsISZ998FTGtwHNxwXyISel+9R4hJYtp+y1tmXo=
  app: UVA-Craigslist
  on:
    repo: uva-cs3240-f19/UVA-Craigslist
